version: '3'
services:
  #database
  db:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: investment
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - cryptosite
  #apache
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '3600:80'
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - cryptosite
networks:
  cryptosite:
volumes:
  db_data:
    
    

